syntax = "proto3";

option csharp_namespace = "GrpcGameInteractionClient";

package game_interaction;

service GameInteraction {
  rpc CreateRoom(GrpcCreateRoomRequest) returns (GrpcCreateRoomResponse);

  rpc JointToRoom(GrpcJoinToRoomRequest) returns (GrpcJoinToRoomResponse);
}

// -------------- CreateRoom --------------
message GrpcCreateRoomRequest {
  CreateRoomRequest create_room_request = 1;
  string connection_id = 2;
}

message GrpcCreateRoomResponse {
  bool success = 1;
}

message RoomRequest {
  string room_name = 1;
  int32 room_size = 2;
  int32 start_bid = 3;
  int32 min_bid = 4;
  int32 max_bid = 5;
  string avatar_url = 6;
  string status = 7;
  int32 player_in_room = 8;
}

message CreateRoomRequest {
  RoomRequest room_request = 1;
  string playerId = 2;
  int32 selected_start_money = 3;
  int32 upper_bound = 4;
  int32 lower_bound = 5;
}

// -------------- JoinToRoom --------------
message GrpcJoinToRoomRequest {
  string room_id = 1;
  string player_id = 2;
  int32 selected_start_money = 3;
  string connection_id = 4;
}

message GrpcJoinToRoomResponse {
  bool success = 1;
}
