syntax = "proto3";

option csharp_namespace = "IdentityClient";

package identity;

service Identity {
    rpc Authenticate (AuthenticateRequest) returns (AuthenticateResponse);

    rpc Register (RegisterRequest) returns (RegisterResponse);

    rpc RefreshToken (RefreshTokenRequest) returns (RefreshTokenResponse);

    rpc Revoke (RevokeRequest) returns (RevokeResponse);

    rpc RevokeAll(RevokeAllRequest) returns (RevokeAllResponse);
}

message AuthenticateRequest {
    string email = 1;
    string password = 2;
}

message PlayerInfoResponse {
    string id = 1;
    string avatar_url = 2;
    string player_name = 3;
    int32 matches = 4;
    int32 loses = 5;
    int32 wins = 6;
    int32 draws = 7;
    int32 all_exp = 8;
    int32 current_exp = 9;
    int32 target_exp = 10;
    int32 money = 11;
    int32 likes = 12;
    int32 level = 13;
    int32 has21 = 14;
}

message AuthenticateResponse {
    string player_id = 1;
    string player_name = 2;
    string email = 3;
    string token = 4;
    string refresh_token = 5;
    PlayerInfoResponse player_info = 6;
}

message RegisterRequest {

}

message RegisterResponse {

}

message RefreshTokenRequest {

}

message RefreshTokenResponse {

}

message RevokeRequest {

}

message RevokeResponse {

}

message RevokeAllRequest {

}

message RevokeAllResponse {

}