<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation" Version="11.9.0" />
      <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.9.0" />
      <PackageReference Include="Grpc.Core.Api" Version="2.62.0" />
      <PackageReference Include="Mediator.Abstractions" Version="2.1.7" />
      <PackageReference Include="Microsoft.AspNetCore.App" Version="2.2.8" />
      <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.15.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\..\BuildingBlocks\Core\Core.csproj" />
      <ProjectReference Include="..\App.Contracts\App.Contracts.csproj" />
      <ProjectReference Include="..\App.Domain\App.Domain.csproj" />
      <ProjectReference Include="..\App.GrpcClient\App.GrpcClient.csproj" />
      <ProjectReference Include="..\App.SignalR\App.SignalR.csproj" />
    </ItemGroup>

</Project>
