services:
  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5001:80"
      - "5002:443"
  
  client:
#    volumes:
#      - /Users/Harlok/.aspnet/https:/app
    environment:
      - WDS_SOCKET_PORT=3000
    ports:
      - "5003:3000"
  
  proxy:
    volumes:
      - ../api-gateways/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"