<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Mediator.Abstractions" Version="2.1.7" />
      <PackageReference Include="Microsoft.AspNetCore.App" Version="2.2.8" />
      <PackageReference Include="Serilog" Version="3.1.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\App.Contracts\App.Contracts.csproj" />
      <ProjectReference Include="..\App.Domain\App.Domain.csproj" />
    </ItemGroup>

</Project>
