<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net7.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.15" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="7.0.15">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.15">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="7.0.11" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\UserInteraction.Application\UserInteraction.Application.csproj" />
      <ProjectReference Include="..\UserInteraction.Contracts\UserInteraction.Contracts.csproj" />
      <ProjectReference Include="..\UserInteraction.Domain\UserInteraction.Domain.csproj" />
    </ItemGroup>

</Project>
